RA.Web/Controllers/AnalyseController.cs
using Microsoft.AspNet.Identity;
using RA.Web.App_Code;
using RA.Web.Models;
using RA.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace RA.Web.Controllers
{
    [Authorize]
    public class AnalyseController : Controller
    {
        private String getYear()
        {
            if (Session["year"] == null)
            {
                if (Response.Cookies.Get("year").Value == null)
                {
                    Response.Cookies.Add(new HttpCookie("year", DateTimeOffset.Now.Year.ToString()));
                    Session["year"] = DateTime.Now.Year;
                }
                else
                    Session["year"] = Response.Cookies.Get("year").Value;
            }

            return Session["year"].ToString();
        }

        //
        // GET: /Analyse/
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(String year)
        {
            Session["year"] = year;
            Response.Cookies.Add(new HttpCookie("year", year));
            return View();
        }

        //
        // GET: /Analyse/Upload
        public ActionResult Upload()
        {
            ViewBag.Message = "Welcome to result Uploader";
            return View();
        }


        //
        // POST: /Analyse/Upload
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file, String year)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var intyear = int.Parse(year);
                } catch(Exception ex)
                {
                    year = System.DateTime.Now.Year.ToString();
                }

                if (file != null)
                {
                    var fileName = User.Identity.Name + Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName);
                    file.SaveAs(path);
                    AnalyseResult ar = new AnalyseResult(User.Identity.GetUserId(), year);
                    ar.BeginAnalysing(path);
                    ViewBag.Message = "Analysis Successful";
                    return View();
                }
                else
                {
                    ViewBag.Message = "Please Choose a File";
                    return View();
                }
            }

            // If We reached here Something Went wrong
            ViewBag.Message = "Something Went Wrong! Please Try Again";
            return View();
        }


        //
        // GET: School Summary
        public ActionResult SchoolSummary()
        {

            PrepareSchoolSummary pss = new PrepareSchoolSummary(User.Identity.GetUserId(), getYear());
            SchoolSummaryVM model = pss.prepare();
            return View(model);
        }

        //
        // GET: /Analyse/SubjectSumamry
        public ActionResult SubjectSummary()
        {
            PrepareSubjectSummary pss = new PrepareSubjectSummary(User.Identity.GetUserId(), getYear());
            IEnumerable<String> subjectCodes = pss.GetSubjectCodes();
            ViewBag.subjectCodes = subjectCodes;
            return View();
        }

        //
        // POST: /Analyse/SubjectSummary
        [HttpPost]
        public ActionResult SubjectSummary(String SubjectCode)
        {
            PrepareSubjectSummary pss = new PrepareSubjectSummary(User.Identity.GetUserId(), getYear());
            var tokens = SubjectCode.Split(' ');
            return View(pss.prepare(tokens[0]));
        }

        public ActionResult StudentSummary()
        {
            PrepareStudentSummary pss = new PrepareStudentSummary(User.Identity.GetUserId(), getYear());
            return View(pss.prepare());
        }

        public ActionResult SectionSummary()
        {
            PrepareSectionSummary pss = new PrepareSectionSummary(User.Identity.GetUserId(), getYear());
            List<String> sections = pss.getSections();
            ViewBag.sectionnames = sections;
            return View();
        }

        [HttpPost]
        public ActionResult SectionSummary(String Section)
        {
            PrepareSectionSummary pss = new PrepareSectionSummary(User.Identity.GetUserId(), getYear());
            return View(pss.prepare(Section));
        }

        public ActionResult UpdateSectionDetails()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UpdateSectionDetails(UpdateSectionDetailsVM model)
        {
            UpdateSectionDetails usd = new UpdateSectionDetails(model, User.Identity.GetUserId(),getYear());
            usd.Update();

            return RedirectToAction("Index");
        }

        public ActionResult Toppers()
        {
            PrepareToppers pt = new PrepareToppers(User.Identity.GetUserId(), getYear());
            return View(pt.prepare());
        }
    }
}

RA.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Result Analyzer</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/carousel.css" />
</head>
<body>
    <!--Nevigation Bar-->
    <div class="navbar-wrapper">
        <div class="container">
            <div class="navbar navbar-inverse navbar-static-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="~/">Result Analyzer</a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>
                                <a href="~/Analyse/">Home</a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Analyse <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="~/Analyse/">Home</a></li>
                                    <li>@Html.ActionLink("School Summary", "SchoolSummary", "Analyse")</li>
                                    <li>@Html.ActionLink("Toppers List", "Toppers", "Analyse")</li>
                                    <li>@Html.ActionLink("Subject Summary", "SubjectSummary", "Analyse")</li>
                                    <li>@Html.ActionLink("Roll Sheet Percentage Wise", "StudentSummary", "Analyse")
                                    <li>@Html.ActionLink("Section Summary", "SectionSummary", "Analyse")</li>
                                    <li class="divider"></li>
                                    <li>@Html.ActionLink("Upload Result", "Upload", "Analyse")</li>
                                    <li>@Html.ActionLink("Update Section Details", "UpdateSectionDetails", "Analyse")</li>
                                </ul>
                            </li>
                        </ul>
                        @RenderPage("_LoginPartial.cshtml")
                    </div>
                </div>
            </div>
        </div>
    </div> 
    <!-- Nagivation bar End-->

    @RenderSection("Featured", required: false)
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Result Analyzer</p>
            <p>Developed and maintained by Ankur Tyagi</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>